 services:
  mongo:
      build:
        context: .
        args:
          MONGO_VERSION: ${MONGO_VERSION}
      environment:
        MONGO_USERNAME: ${MONGO_USERNAME}
        MONGO_PASSWORD: ${MONGO_PASSWORD}
        MONGO_REPLICA_HOST: localhost
        MONGO_REPLICA_PORT: ${MONGO_PORT}
        MONGO_COMMAND: ${MONGO_COMMAND}
      ports:
        - '${MONGO_PORT}:27017'
      restart: unless-stopped
      healthcheck:
        # Use "mongo" instead of "mongosh" before v5.0
        test: ['CMD', '${MONGO_COMMAND}', 'admin', '--port', '27019', '--eval', "db.adminCommand('ping').ok"]
        interval: 5s
        timeout: 2s
        retries: 20